export const states = [
  { id: 1, long_name: 'Alabama', short_name: 'Ala.', code: 'AL' },
  { id: 2, long_name: 'Alaska', short_name: 'Alaska', code: 'AK' },
  { id: 3, long_name: 'Arizona', short_name: 'Ariz.', code: 'AZ' },
  { id: 4, long_name: 'Arkansas', short_name: 'Ark.', code: 'AR' },
  { id: 5, long_name: 'California', short_name: 'Calif.', code: 'CA' },
  { id: 6, long_name: 'Colorado', short_name: 'Colo.', code: 'CO' },
  { id: 7, long_name: 'Connecticut', short_name: 'Conn.', code: 'CT' },
  { id: 8, long_name: 'Delaware', short_name: 'Del.', code: 'DE' },
  { id: 9, long_name: 'Florida', short_name: 'Fla.', code: 'FL' },
  { id: 10, long_name: 'Georgia', short_name: 'Ga.', code: 'GA' },
  { id: 11, long_name: 'Hawaii', short_name: 'Hawaii', code: 'HI' },
  { id: 12, long_name: 'Idaho', short_name: 'Idaho', code: 'ID' },
  { id: 13, long_name: 'Illinois', short_name: 'Ill.', code: 'IL' },
  { id: 14, long_name: 'Indiana', short_name: 'Ind.', code: 'IN' },
  { id: 15, long_name: 'Iowa', short_name: 'Iowa', code: 'IA' },
  { id: 16, long_name: 'Kansas', short_name: 'Kans.', code: 'KS' },
  { id: 17, long_name: 'Kentucky', short_name: 'Ky.', code: 'KY' },
  { id: 18, long_name: 'Louisiana', short_name: 'La.', code: 'LA' },
  { id: 19, long_name: 'Maine', short_name: 'Maine', code: 'ME' },
  { id: 20, long_name: 'Maryland', short_name: 'Md.', code: 'MD' },
  { id: 21, long_name: 'Massachusetts', short_name: 'Mass.', code: 'MA' },
  { id: 22, long_name: 'Michigan', short_name: 'Mich.', code: 'MI' },
  { id: 23, long_name: 'Minnesota', short_name: 'Minn.', code: 'MN' },
  { id: 24, long_name: 'Mississippi', short_name: 'Miss.', code: 'MS' },
  { id: 25, long_name: 'Missouri', short_name: 'Mo.', code: 'MO' },
  { id: 26, long_name: 'Montana', short_name: 'Mont.', code: 'MT' },
  { id: 27, long_name: 'Nebraska', short_name: 'Neb.', code: 'NE' },
  { id: 28, long_name: 'Nevada', short_name: 'Nev.', code: 'NV' },
  { id: 29, long_name: 'New Hampshire', short_name: 'N.H.', code: 'NH' },
  { id: 30, long_name: 'New Jersey', short_name: 'N.J.', code: 'NJ' },
  { id: 31, long_name: 'New Mexico', short_name: 'N.Mex.', code: 'NM' },
  { id: 32, long_name: 'New York', short_name: 'N.Y.', code: 'NY' },
  { id: 33, long_name: 'North Carolina', short_name: 'N.C.', code: 'NC' },
  { id: 34, long_name: 'North Dakota', short_name: 'N.Dak.', code: 'ND' },
  { id: 35, long_name: 'Ohio', short_name: 'Ohio', code: 'OH' },
  { id: 36, long_name: 'Oklahoma', short_name: 'Okla.', code: 'OK' },
  { id: 37, long_name: 'Oregon', short_name: 'Ore.', code: 'OR' },
  { id: 38, long_name: 'Pennsylvania', short_name: 'Pa.', code: 'PA' },
  { id: 39, long_name: 'Rhode Island', short_name: 'R.I.', code: 'RI' },
  { id: 40, long_name: 'South Carolina', short_name: 'R.I.', code: 'SC' },
  { id: 41, long_name: 'South Dakota', short_name: 'S.Dak.', code: 'SD' },
  { id: 42, long_name: 'Tennessee', short_name: 'Tenn.', code: 'TN' },
  { id: 43, long_name: 'Texas', short_name: 'Tex.', code: 'TX' },
  { id: 44, long_name: 'Utah', short_name: 'Utah', code: 'UT' },
  { id: 45, long_name: 'Vermont', short_name: 'Vt.', code: 'VT' },
  { id: 46, long_name: 'Virginia', short_name: 'Va.', code: 'VA' },
  { id: 47, long_name: 'Washington', short_name: 'Wash.', code: 'WA' },
  { id: 48, long_name: 'West Virginia', short_name: 'W.Va.', code: 'WV' },
  { id: 49, long_name: 'Wisconsin', short_name: 'Wis.', code: 'WI' },
  { id: 50, long_name: 'Wyoming', short_name: 'Wyo.', code: 'WY' },
];
